# -*- coding: utf-8 -*-
"""final02.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EpRYrwTGFuHvAkBsPEf8_6wu9dBvAbby
"""

print("Hello!")
name_user = input("What is your name? : ")
print("Nice to meet you", name_user)
print("\nWelcome to Age Calculator Program")
print("Made By Chirwat Labying M.4/4")

birth_year = int(input("\nPlease enter your birth year : "))
current_year = 2026
age = current_year - birth_year
print("Your age is", age)

from datetime import datetime

print("===================================")
print("        AGE CALCULATOR PROGRAM     ")
print("===================================")

name_user = input("What is your name? : ")
print(f"\nNice to meet you, {name_user} 😊")

while True:
    try:
        print("\nEnter your birth date")
        birth_day = int(input("Day (1-31): "))
        birth_month = int(input("Month (1-12): "))
        birth_year = int(input("Year (e.g. 2008): "))

        birth_date = datetime(birth_year, birth_month, birth_day)
        today = datetime.now()

        if birth_date > today:
            print("Birth date cannot be in the future! Please try again.\n")
        else:
            break

    except ValueError:
        print("Invalid date! Please enter correct numbers.\n")

# คำนวณอายุแบบ ปี เดือน วัน
years = today.year - birth_date.year
months = today.month - birth_date.month
days = today.day - birth_date.day

if days < 0:
    months -= 1
    # จำนวนวันของเดือนก่อนหน้า
    previous_month = today.month - 1 if today.month > 1 else 12
    previous_year = today.year if today.month > 1 else today.year - 1
    days_in_previous_month = (datetime(previous_year, previous_month % 12 + 1, 1) - datetime(previous_year, previous_month, 1)).days
    days += days_in_previous_month

if months < 0:
    years -= 1
    months += 12

print("\n========== RESULT ==========")
print(f"Hello {name_user}, you are:")
print(f"{years} years, {months} months, and {days} days old 🎉")
print("============================")