# -*- coding: utf-8 -*-
"""final02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EpRYrwTGFuHvAkBsPEf8_6wu9dBvAbby
"""

print("Hello!")
name_user = input("What is your name? : ")
print("Nice to meet you", name_user)
print("\nWelcome to Age Calculator Program")
print("Made By Chirwat Labying M.4/4")

birth_year = int(input("\nPlease enter your birth year : "))
current_year = 2026
age = current_year - birth_year
print("Your age is", age)
